name: Collect OCI Container Logs
author: andrewazores
description: Collect logs from all OCI containers.
inputs:
  cmd:
    description: |
      The OCI runtime command to use. If not provided, defaults to `docker`.
  dest:
    description: |
      Destination folder to write to. If not provided, logs will be
      written to stdout. If provided, the folder will be created if it doesn't
      exist, and files will be written based on container names (e.g. 'redis.log').
  shell:
    description: |
      Shell to execute commands.  Defaults to "/bin/sh".
  images:
    description: |
      A comma delimited list of image names. If provided, only output
      from containers with these images will be shown. Containers will match if
      the image matches exactly (e.g. "mongo:3.4.22") or if the image name matches
      without a tag (e.g. "mongo" will match "mongo:3.4.22").

runs:
  using: node12
  main: 'main.js'
branding:
  icon: align-left
  color: blue
